### ISSUE TITLE
Amounts are not displayed properly

### ISSUE THREAD

**Issue by mradkov** [waellet/waellet#232]
![image](https://user-images.githubusercontent.com/13139371/70787477-66c9f480-1d97-11ea-9057-4e9a06042438.png)

**Comment by petbaik** [comment]
After fixing this https://github.com/waellet/waellet/issues/216 amount in Aepp should be passed in aettos. Passing **1** as amount will lead to this improper format, because **1** in aettos is very low value. For sending **1 AE** ,   **1000000000000000000** should be passed. 
Is it the same case in this issue?

**Comment by mradkov** [comment]
Yes, I think this is fixed now, is it?

**Comment by mradkov** [comment]
We should probably setup some library in the nearest future for handling the different denominations in aettos, microAE, picoAE and else. 

Closing this for now.
